<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class mahasiswaSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('mahasiswa')->insert([
            [
                // 2014
                'nim' => "11S14017",
                'nama' => "Amanda Fujiyanti",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14059",
                'nama' => "Amrianto Saragih",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14032",
                'nama' => "Andi Marthin Pandapotan",
                'angkatan' => 2014,
                'status' => "Mengundurkan Diri",
            ],
            [
                'nim' => "11S14014",
                'nama' => "Anggeliana Zain",
                'angkatan' => 2014,
                'status' => "Mengundurkan Diri",
            ],
            [
                'nim' => "11S14048",
                'nama' => "Apria Theovani Nainggolan",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14044",
                'nama' => "AArtia Claudia Siregar",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14013",
                'nama' => "Astri Neva Y. Sibuea",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14060",
                'nama' => "Bernando Lumban Raja",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14029",
                'nama' => "Betty Chrisda Yanti Sinaga",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14058",
                'nama' => "Boy Suganda Sinaga",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14011",
                'nama' => "Budianto Sentosa",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14024",
                'nama' => "Daniel Giovanni Sinaga",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14016",
                'nama' => "Daniel Somanta Purba",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14020",
                'nama' => "Davit Syahputra Napitupulu",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14038",
                'nama' => "ADesi Elfrida Silaban",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14006",
                'nama' => "Desi Roulita Pakpahan",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14001",
                'nama' => "Dewi Kartika Marpaung",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14033",
                'nama' => "Dian Agil Saputra Panggabean",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14021",
                'nama' => "Dian Malela Napitupulu",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14012",
                'nama' => "Esri Analiza Pane",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14050",
                'nama' => "Febry Saputra Manik",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14036",
                'nama' => "Frans Togu Tua Marbun",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14046",
                'nama' => "Gideon Dirgahayu Manurung",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14003",
                'nama' => "AGiovani Lasberia Butarbutar",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14015",
                'nama' => "Grace Bumegah Sianturi",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14025",
                'nama' => "Gracia Hutapea",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14002",
                'nama' => "H. Justin Manurung",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14027",
                'nama' => "Helkia Pasaribu",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14031",
                'nama' => "Immanuel Septario Sitanggang",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14030",
                'nama' => "Ivan Sebastian Marbun",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14057",
                'nama' => "Jaya Haryono Manik",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14043",
                'nama' => "Johan Enrico",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14008",
                'nama' => "Kwatri Sabattyan Nainggolan",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14028",
                'nama' => "Lily Andayani Tampubolon",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14039",
                'nama' => "Lukas Sinambela",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14055",
                'nama' => "Maxwel Natanael Munthe",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14023",
                'nama' => "Melvandito Oktavian Parlindungan Simanjuntak",
                'angkatan' => 2014,
                'status' => "Lulus",
            ],
            [
                'nim' => "11S14035",
                'nama' => "Michael Arianto",
                'angkatan' => 2014,
                'status' => "Mengundurkan Diri",
            ],
            [
                'nim' => '11S14019',
                'nama' => 'Minarni Debora Harahap',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14056',
                'nama' => 'Minarti Siahaan',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14010',
                'nama' => 'Norlina Pasaribu',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14045',
                'nama' => 'Notarista Magdalena Silaban',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14047',
                'nama' => 'ANovendra Sirait',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14004',
                'nama' => 'Oktavi Yanty Elisabeth Silitonga',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14053',
                'nama' => 'Paradena Kharismasio Turnip',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14022',
                'nama' => 'Paul Situmorang',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14041',
                'nama' => 'Rajasa Nagara E.R Silitonga',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14009',
                'nama' => 'Ranty Deviana Siahaan',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14005',
                'nama' => 'Romasi Gohanna Sibarani',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14042',
                'nama' => 'Rudi Butar Butar',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14026',
                'nama' => 'Sandro Y. M. Nababan',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14040',
                'nama' => 'Surya Miro Chardo Purba',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14018',
                'nama' => 'Talenta Palentina Pardede',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14049',
                'nama' => 'Titin Desriana Ompusunggu',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14051',
                'nama' => 'Tongon Alexsander Pardede',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14037',
                'nama' => 'Vera Agustinova Sirait',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14052',
                'nama' => 'Wahyu Adi P. Nainggolan',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14034',
                'nama' => 'Wira Putrawan Pakpahan',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14054',
                'nama' => 'Yan Ramadaniel Christoper Pane',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S14007',
                'nama' => 'Yosepina Lumbantobing',
                'angkatan' => 2014,
                'status' => 'Lulus',
            ],

            // 2015
            [
                'nim' => '11S15025',
                'nama' => 'Ade Erispra Rismanda',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15062',
                'nama' => 'Adrian Jeremy Partogi Sirait',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15041',
                'nama' => 'Agustin Widjayanti',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15046',
                'nama' => 'Andrey Cristian Libriando Sembiring',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15023',
                'nama' => 'Bayu Prasetyo Raharjo',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15030',
                'nama' => 'Bayu Theo Bryantinus Hutajulu',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15054',
                'nama' => 'Bryan Agrisendi Manurung',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15004',
                'nama' => 'Cindy Patricia Stepany Siringoringo',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15017',
                'nama' => 'Daniel Bos Putera Panggabean',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15061',
                'nama' => 'David Nobel Sihite',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15010',
                'nama' => 'Debora Rodearna Simarmata',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15005',
                'nama' => 'Debora S. Sitanggang',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15035',
                'nama' => 'Devi Andriani Sirait',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15015',
                'nama' => 'Devi Pakpahan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15021',
                'nama' => 'Dian Sinta Sianturi',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15047',
                'nama' => 'Elida Simangunsong',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15003',
                'nama' => 'Emma Hannisa Laurencia Nainggolan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15026',
                'nama' => 'Eva Mart Novianti',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15058',
                'nama' => 'Felix Oswaldo Siburian',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15011',
                'nama' => 'Franky Napitupulu',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15034',
                'nama' => 'Hanson Siagian',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15053',
                'nama' => 'Haposan Parulian Siahaan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15050',
                'nama' => 'Harry Dendi Simanjuntak',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15048',
                'nama' => 'Hendro Prabowo .T',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15060',
                'nama' => 'Heri Wardana Ginting',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15007',
                'nama' => 'Herlina Meilani Panjaitan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15022',
                'nama' => 'Hisartua Panca Putra Sitorus Pane',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15039',
                'nama' => 'Hizkia Ricky F Parhusip',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15052',
                'nama' => 'Ignatius Gonzales Sitorus',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15055',
                'nama' => 'Immanuel Riyadi Tampubolon',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15002',
                'nama' => 'Indra Novita D. Simanjuntak',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15018',
                'nama' => 'Indy Victoria Widya',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15014',
                'nama' => 'Ivana Natalia Gabriella Situmorang',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15016',
                'nama' => 'Jhoan River S',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15027',
                'nama' => 'Jonathan Hamonangan Silalahi',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15042',
                'nama' => 'Joshua Surya Ananta Sitanggang',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15059',
                'nama' => 'Kevin J F Pardamaian S',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15006',
                'nama' => 'Khairani Malau',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15051',
                'nama' => 'Lohot Bintangur Siboro',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15063',
                'nama' => 'Markus Givari Hasibuan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15043',
                'nama' => 'Martha Febri Jesica Pangaribuan',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15009',
                'nama' => 'Miranda Anjelina Parhusip',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15040',
                'nama' => 'Monika Siregar',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15065',
                'nama' => 'Noorman Paul Aritonang',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15044',
                'nama' => 'Oktavianti Debora Siahaan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15037',
                'nama' => 'Oriana Oktaviana Sihaloho',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15020',
                'nama' => 'Pratiwi Mey Putri Hutagaol',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15064',
                'nama' => 'Rade Rido',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15045',
                'nama' => 'Reikard Martua Napitupulu',
                'angkatan' => 2015,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S15024',
                'nama' => 'Ricky Halomoan Tampubolon',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15031',
                'nama' => 'Rizesky N Siallagan',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15057',
                'nama' => 'Roby Nolan Parapat',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15013',
                'nama' => 'Ronald Josua Halomoan Hutajulu',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15056',
                'nama' => 'Ruben Parlindungan Ambarita',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15049',
                'nama' => 'Russell Buena Basadena Ayub Hutasoit',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15033',
                'nama' => 'Samuel Septian Sitorus',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15001',
                'nama' => 'Santi Oktavia Siagian',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15032',
                'nama' => 'Sapto Gokma Dominggus Sirait',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15029',
                'nama' => 'Suci Lestari',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15019',
                'nama' => 'Sudarsono Sianipar',
                'angkatan' => 2015,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S15028',
                'nama' => 'Tiffany Alesti Siahaan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15012',
                'nama' => 'Tua Roy Sariyedi Situmorang',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15008',
                'nama' => 'Veronika Tambunan',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15038',
                'nama' => 'Willy Yunus S Manurung',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S15036',
                'nama' => 'Yosianna Br Sembiring',
                'angkatan' => 2015,
                'status' => 'Lulus',
            ],

            // 2016
            [
                'nim' => '11S16032',
                'nama' => 'Achmad Yusuf Nasution',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16019',
                'nama' => 'Adi Parmanto Sagala',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16030',
                'nama' => 'Adrian Setiyadi Sitorus',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16033',
                'nama' => 'Alma Laura Sinaga',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16008',
                'nama' => 'Amzesmoro Sianturi',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16038',
                'nama' => 'Andre Maniti Hasibuan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16053',
                'nama' => 'Andre Yehuda Sitorus',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16002',
                'nama' => 'Andreas Siahaan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16051',
                'nama' => 'Anggiat Maruli Tua M',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16014',
                'nama' => 'Anita Paulina Kristina Sitorus',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16013',
                'nama' => 'Asima Trisnawati Nababan',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16044',
                'nama' => 'Azriel Situmorang',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16011',
                'nama' => 'Brham Hansen Manurung',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16003',
                'nama' => 'Cahaya Julinar Pakpahan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16048',
                'nama' => 'Christine Olga Panjaitan',
                'angkatan' => 2016,
                'status' => 'Tunda Unri',
            ],
            [
                'nim' => '11S16020',
                'nama' => 'Crismon Nagara Manalu',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16037',
                'nama' => 'David Criston H Purba',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16064',
                'nama' => 'Dian Samuel Perisai Sormin',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16042',
                'nama' => 'Ditto Yogi Bernadian Silalahi',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16034',
                'nama' => 'Dohar Josua.N',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16063',
                'nama' => 'Dolly Lesmana',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16046',
                'nama' => 'Edward Hasiholan Simanjuntak',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16026',
                'nama' => 'Elizabeth Lumban Gaol',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16025',
                'nama' => 'Emrycho C J Simanungkalit',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16050',
                'nama' => 'Evrin Lumbantobing',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16012',
                'nama' => 'Febrina Siagian',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16060',
                'nama' => 'Felix Aditya Nadeak',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16043',
                'nama' => 'Fernando Panangian Hasugian',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16009',
                'nama' => 'Fitri Rosida Simorangkir',
                'angkatan' => 2016,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S16040',
                'nama' => 'Frans Dedy Pasaribu',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16031',
                'nama' => 'Glory Karina Hotbana Sitohang',
                'angkatan' => 2016,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S16067',
                'nama' => 'Grace Evanggelisa Tambunan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16057',
                'nama' => 'Grecia Elizabeth Situmorang',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16018',
                'nama' => 'Gultom Laurensius Patar',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16029',
                'nama' => 'Hariaty Mangatur Sasha Lumbantobing',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16027',
                'nama' => 'AHaris Prasetya Dharma Syahputra Situmeang',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16017',
                'nama' => 'Herianto Saragi',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16016',
                'nama' => 'Indriani Tiosari Sitorus',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16035',
                'nama' => 'Jeremy Valentin Siahaan',
                'angkatan' => 2016,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S16023',
                'nama' => 'Jhon Cristianto Limbong',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16065',
                'nama' => 'Joko Hermanto Manurung',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16047',
                'nama' => 'Jordy Hutahaean',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16004',
                'nama' => 'Jubey Simanjuntak',
                'angkatan' => 2016,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S16061',
                'nama' => 'ristian Pratama Nainggolan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16066',
                'nama' => 'Lian Agusman Marpaung',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16010',
                'nama' => 'Melissa Panjaitan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16059',
                'nama' => 'Mia Carina Friska Lingga',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16022',
                'nama' => 'MICHAEL.S',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16041',
                'nama' => 'Nico Gorga Soros Panjaitan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16039',
                'nama' => 'Putri Indah Sari S',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16006',
                'nama' => 'Ranti Veronika Sidauruk',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16052',
                'nama' => 'Refly Alexsander Marcellino',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16058',
                'nama' => 'Reynaldo Cristinus Hutahaean',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16054',
                'nama' => 'Rumondang Agustina Limbong',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16021',
                'nama' => 'Rut Rilis Tambunan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16056',
                'nama' => 'Ruthya P. D. Aruan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16055',
                'nama' => 'Samuel Alfredo Astrada Napitupulu',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16001',
                'nama' => 'Sandra Yogi F. Simangunsong',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16015',
                'nama' => 'Sanny Era Eliza Siallagan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16036',
                'nama' => 'Tangido Halomoan Sinaga',
                'angkatan' => 2016,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S16024',
                'nama' => 'Wisda Simanjuntak',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16005',
                'nama' => 'Yohana Imelda Lubis',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16007',
                'nama' => 'Yohannes Nababan',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16049',
                'nama' => 'Yopi Andrew Saragih',
                'angkatan' => 2016,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S16062',
                'nama' => 'Yosua Giat Raja Saragih',
                'angkatan' => 2016,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S16045',
                'nama' => 'Yudika Ekaputra Martupatua Sitorus',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S16028',
                'nama' => 'Zico Enrique Bukit',
                'angkatan' => 2016,
                'status' => 'Mengundurkan Diri',
            ],

            // 2017
            [
                'nim' => '11S17053',
                'nama' => 'Oky Firdaus Purba',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17013',
                'nama' => 'Melani Isabella Siregar',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17054',
                'nama' => 'Jenny Marilin Uli Hutasoit',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17058',
                'nama' => 'Sepriana Carolina',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17061',
                'nama' => 'Geby Chrysania Purba',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17065',
                'nama' => 'Grace Margaret Sihite',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17018',
                'nama' => 'D. Welvin Hutagalung',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17023',
                'nama' => 'Immanuel Julius Adik Putra Siburian',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17022',
                'nama' => 'Febian Joshua Reynara',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17025',
                'nama' => 'Bony Yudha Sinurat',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17046',
                'nama' => 'Maghel Heans Gultom',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17063',
                'nama' => 'Vikki Parlindungan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17003',
                'nama' => 'Esra Delima Manurung',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17004',
                'nama' => 'Helda Agave Sihombing',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17014',
                'nama' => 'Amelia Septiani',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17040',
                'nama' => 'Gracella Romauly Tambunan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17060',
                'nama' => 'Clara Fellysa Simanjuntak',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17009',
                'nama' => 'Albert P. Simanjuntak',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17028',
                'nama' => 'Angel Alicya Lumiana Napitupulu',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17042',
                'nama' => 'Nina Ismaya Pangaribuan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17008',
                'nama' => 'Firman Maranatha Sihombing',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17017',
                'nama' => 'Immanuel Farhan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17024',
                'nama' => 'Ebenezer',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17026',
                'nama' => 'Eriel Kristo Uluan Siagian',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17027',
                'nama' => 'Doni Albert Hasiholan Panggabean',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17029',
                'nama' => 'Grady Sianturi',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17036',
                'nama' => 'Abednego Sihombing',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17038',
                'nama' => 'Willy Jems Gurning',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17041',
                'nama' => 'Joshua Alexander Sinaga',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17047',
                'nama' => 'Jhonathan Harry Dea Simatupang',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17050',
                'nama' => 'Efren Manalu',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17052',
                'nama' => 'Alek Sander Simbolon',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17055',
                'nama' => 'Ishak Jefferson Panjaitan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17056',
                'nama' => 'Juan Jasa Putra Sinurat',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17059',
                'nama' => 'Ivan Felix Sinaga',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17064',
                'nama' => 'Januard Pardo Lumbangaol',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17066',
                'nama' => 'Pangondion Kurniawan Naibaho',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17001',
                'nama' => 'Grace Yola Lumbantoruan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17002',
                'nama' => 'Dian Widya F. Sitorus',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17005',
                'nama' => 'Juliana Siagian',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17011',
                'nama' => 'Triska Paskah Uli Pangaribuan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17012',
                'nama' => 'Wira Epriana Ambarita',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17015',
                'nama' => 'Sulastri Tambunan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17019',
                'nama' => 'Leonyzkia Elyzabeth Mahardhyka Hutapea',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17021',
                'nama' => 'Maria Zanissa Hutagalung',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17032',
                'nama' => 'Dian Kristy Pasaribu',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17034',
                'nama' => 'Monica Dewi Sartika Marpaung',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17037',
                'nama' => 'Ivani Firous Purba',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17045',
                'nama' => 'Netty Togi Marito Siahaan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S17048',
                'nama' => 'Christina Vitaloka Panjaitan',
                'angkatan' => 2017,
                'status' => 'Lulus',
            ],

            // 2018
            [
                'nim' => '11S18026',
                'nama' => 'Ivan Johannes Alexander Harahap',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18032',
                'nama' => 'Rido Sitanggang',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18033',
                'nama' => 'Putra Pangabahan Sitorus',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18037',
                'nama' => 'Hisar Haryanto Sinaga',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18047',
                'nama' => 'Timothy Owen',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18015',
                'nama' => 'Yanada Sari Br Situmorang',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18044',
                'nama' => 'Ananda Amelia Mustika Maherani',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18053',
                'nama' => 'Ika Fransiska Rehulina Perangin Angin',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18057',
                'nama' => 'Marlyse Elysabeth Sitorus',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18023',
                'nama' => 'Jhon Videlis Simamora',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18045',
                'nama' => 'Gorga Deo Salomo Siagian',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18065',
                'nama' => 'Putra Patakkas Gabe Harianja',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18066',
                'nama' => 'Jumadi Heryanto Damanik',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18008',
                'nama' => 'Andrini Mayetha Panjaitan',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18011',
                'nama' => 'Awit Hutabalian',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18052',
                'nama' => 'Ester Martogi Uli Gultom',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18054',
                'nama' => 'Cindy Lucia Simanihuruk',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18062',
                'nama' => 'Devita Yolanda Tampubolon',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18031',
                'nama' => 'Ruth Grace Silvia Br Tobing',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18005',
                'nama' => 'Abdullah Ubaid',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18006',
                'nama' => 'Albert Jeremi Manurung',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18007',
                'nama' => 'Aldi Irvan Siagian',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18014',
                'nama' => 'Jose Marchelino Situmorang',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18024',
                'nama' => 'Aprialdy Sembiring',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18025',
                'nama' => 'Vincentius Jordan Halomoan Tampubolon',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18042',
                'nama' => 'David Basa Halomoan',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18034',
                'nama' => 'Imam Aprido Simarmata',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18046',
                'nama' => 'Simson Fransisco Panjaitan',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18048',
                'nama' => 'Romual Naibaho',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18049',
                'nama' => 'Reinhard Silaen',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18051',
                'nama' => 'Auro Daniel Ersa Silalahi',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18058',
                'nama' => 'Leonardo Robinsar Agustinus Sianturi',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18061',
                'nama' => 'Surya Ferary Nainggolan',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18064',
                'nama' => 'Michael Yerikho Henokh Siahaan',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18067',
                'nama' => 'Irvandi Amir Hamzah Sihombing',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18001',
                'nama' => 'Efrica Cahyani Situmeang',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18002',
                'nama' => 'Putri Era Waty Bakara',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18003',
                'nama' => 'Febby Irene V. Siringoringo',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18009',
                'nama' => 'Easy Destini Manik',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18010',
                'nama' => 'N. Priskila Napitupulu',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18013',
                'nama' => 'Grace Noelia Simorangkir',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18012',
                'nama' => 'Suryani Vebhitry Siahaan',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18019',
                'nama' => 'Deby Tirsah Febrianti Br Siburian',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18020',
                'nama' => 'Fitri Yunita Aritonang',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18022',
                'nama' => 'Devi Wahyuni Silitonga',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18027',
                'nama' => 'Romauli Siagian',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18028',
                'nama' => 'Naomi Tambunan',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18038',
                'nama' => 'Grace Winda Nissi Naibaho',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18041',
                'nama' => 'Grace Widya Simanjuntak',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18040',
                'nama' => 'Anjel Riska D. Pardede',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18050',
                'nama' => 'Maxvania Alarice Manurung',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18056',
                'nama' => 'Sri Intan Sinaga',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18059',
                'nama' => 'Kristiane Purba',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18060',
                'nama' => 'Laura Elisabeth Sinaga',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18063',
                'nama' => 'Elyta Junetta Siregar',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18068',
                'nama' => 'Santi Sandryna',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S18069',
                'nama' => 'Dean Efraim Markus Djebatu',
                'angkatan' => 2018,
                'status' => 'Lulus',
            ],

            // 2019
            [
                'nim' => '11S19001',
                'nama' => 'Bungaran Martua Pakpahan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19002',
                'nama' => 'Hans Mayson Pranajaya Situmeang',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19003',
                'nama' => 'Rafelli Simangunsong',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19004',
                'nama' => 'Sophian Kalam Nainggolan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19005',
                'nama' => 'Jhonatan Edward Sitorus',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19006',
                'nama' => 'Daniel Fernandez Lumbanraja',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19007',
                'nama' => 'Tesalonika Siahaan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19008',
                'nama' => 'Rewina Pakpahan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19009',
                'nama' => 'Renta Sri Hertati Sitorus',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19010',
                'nama' => 'Krisna Tampubolon',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19011',
                'nama' => 'Ferdinand Partahi Jaya Tambunan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19012',
                'nama' => 'Willem Alexender Suranta Pinem',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19013',
                'nama' => 'Yosia Sihaloho',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19014',
                'nama' => 'Jonggi Vegas Sitorus',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19016',
                'nama' => 'Timothy Sipahutar',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19017',
                'nama' => 'Montana Gurning',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19018',
                'nama' => 'Juliant Omri C.N.L. Tobing',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19019',
                'nama' => 'Edrei Abiel Benaya Siregar',
                'angkatan' => 2019,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S19020',
                'nama' => 'Talenta Maria Sihotang',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19021',
                'nama' => 'Trivena Yuli Necia Panjaitan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19022',
                'nama' => 'Gabryella Apriani Sinaga',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19023',
                'nama' => 'Sarah Oktavia Br Pasaribu',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19024',
                'nama' => 'Theresia Mega Tiurma Rumapea',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19025',
                'nama' => 'Prawita Dwi Friskilia',
                'angkatan' => 2019,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S19026',
                'nama' => 'Elisa CLaudia Tambunan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19027',
                'nama' => 'Darel Deonaldo Aloysius Pinem',
                'angkatan' => 2019,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S19028',
                'nama' => 'Deiva Imanuela Pasaribu',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19029',
                'nama' => 'Alfrendo Stenley Silalahi',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19030',
                'nama' => 'Yuan Halasan Siagian',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19031',
                'nama' => 'Gunado Siregar',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19032',
                'nama' => 'Fori Okto Pakpahan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19033',
                'nama' => 'Bintang Lbn Raja',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19034',
                'nama' => 'Hotmangasi Manurung',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19035',
                'nama' => 'Rahmad Joko Susilo',
                'angkatan' => 2019,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S19036',
                'nama' => 'Wybren Agung Manik',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19037',
                'nama' => 'Rio Efraim Simanjuntak',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19038',
                'nama' => 'Jogi Arif Guruh Sitinjak',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19039',
                'nama' => 'Albert',
                'angkatan' => 2019,
                'status' => 'Mengundurkan Diri',
            ],
            [
                'nim' => '11S19040',
                'nama' => 'Judah Michael Parluhutan Sitorus',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19041',
                'nama' => 'Rivaldo Gabriel S',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19042',
                'nama' => 'Riski Yan Daniel Simanjuntak',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19043',
                'nama' => 'Hari Dominggo Soarest Joab Siburian',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19044',
                'nama' => 'Sondang Kevin P. Sihaloho',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19045',
                'nama' => 'Josua Gaolus Nainggolan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19046',
                'nama' => 'Deny Ramadhan Pane',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19047',
                'nama' => 'Andreas Hatigoran',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19048',
                'nama' => 'Nicholas Tio Sibarani',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19049',
                'nama' => 'Albet Matthew BEst Nainggolan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19050',
                'nama' => 'Risky Junior Martua Panggabean',
                'angkatan' => 2019,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S19051',
                'nama' => 'Handy Sonflow Sitepu',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19052',
                'nama' => 'Rens Junior Sibarani',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19054',
                'nama' => 'Yoni Herlina Siahaan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19055',
                'nama' => 'Kartika Novia Hutauruk',
                'angkatan' => 2019,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S19057',
                'nama' => 'Hana Maria Siahaan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19058',
                'nama' => 'Yuliana Nainggolan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19059',
                'nama' => 'Puan Maharani Sirait',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19060',
                'nama' => 'Evi Rosalina Silaban',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19061',
                'nama' => 'Agnes Bertua Nababan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19062',
                'nama' => 'Grace Stefani Natalia Pakpahan',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19063',
                'nama' => 'Hanna Suryani Simarmata',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19064',
                'nama' => 'Patricia',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19065',
                'nama' => 'Aryanti Verina Putri Siregar',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19067',
                'nama' => 'Cynthia Veronika Pardede',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],
            [
                'nim' => '11S19068',
                'nama' => 'Tasya Juli Chantika Gurning',
                'angkatan' => 2019,
                'status' => 'Lulus',
            ],

            // 2020
            [
                'nim' => '11S20001',
                'nama' => 'Samuel Adika Lumban Tobing',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20002',
                'nama' => 'Yoel Ganda Aprilco Napitupulu',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20003',
                'nama' => 'Reinhard Hottua S',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20004',
                'nama' => 'Samuel Immanuel Herlinton Sibuea',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20005',
                'nama' => 'Lasria Sri Rezeki Rajagukguk',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20006',
                'nama' => 'Guntur Augustin Sinaga',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20007',
                'nama' => 'Aditya Pratama Gultom',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20008',
                'nama' => 'Ruth Theresia',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20009',
                'nama' => 'Paulina Natasha Panjaitan',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20011',
                'nama' => 'Putri Septina Simamora',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20012',
                'nama' => 'Niar Fujita Simbolon',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20013',
                'nama' => 'Chantika Nadya Serebella P',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20014',
                'nama' => 'Lusye Triksi Pasaribu',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20015',
                'nama' => 'Winanda Greace A. Sinaga',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20016',
                'nama' => 'Nanchy Monika Siadari',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20017',
                'nama' => 'Satria Armando Pakpahan',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20018',
                'nama' => 'Ruth Aulya Silalahi',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20019',
                'nama' => 'Hedrin S. Sitorus',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20020',
                'nama' => 'Roosen Gabriel Manurung',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20021',
                'nama' => 'Rolasta J.A Sitorus',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20022',
                'nama' => 'Zan Peter Silaen',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20023',
                'nama' => 'Natanael Jansudin Siregar',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20024',
                'nama' => 'David Largo',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20025',
                'nama' => 'Anton Roycar Nababan',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20026',
                'nama' => 'Ivanston Simbolon',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20027',
                'nama' => 'Bryand Christofer Sinaga',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20028',
                'nama' => 'Lamboy Albertson Sirait',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20029',
                'nama' => 'Rizal Sahala Bakti',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20030',
                'nama' => 'Vistar Tiop Rajagukguk',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20032',
                'nama' => 'Yosua Putra Wisesa Haloho',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20033',
                'nama' => 'Dian Jorgy Gultom',
                'angkatan' =>    2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20034',
                'nama' => 'Kevin Willys Nathaneil Samosir',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20035',
                'nama' => 'Michael Albert Sholay Napitupulu',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20036',
                'nama' => 'Moranda Haloho',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20037',
                'nama' => 'Fastoria Ginting',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20038',
                'nama' => 'Valentina Margaretha Siahaan',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20039',
                'nama' => 'Ketrina S. Siagian',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20040',
                'nama' => 'Sri Rahayu Saragih',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20041',
                'nama' => 'Fany Tania Lumban Siantar',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20042',
                'nama' => 'Luna Sweeta Anastasya Pangaribuan',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20043',
                'nama' => 'Putri Ruth Berliana Siahaan',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20044',
                'nama' => 'Amelia Agustina Hutajulu',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20046',
                'nama' => 'Rachel Riris Rotua Damanik',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20047',
                'nama' => 'Greyssenly Ester Lya Simanjuntak',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20048',
                'nama' => 'Theresia Yolanda Laura Hutabarat',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20049',
                'nama' => 'Christin Adelia Pratiwi Sihite',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20050',
                'nama' => 'Grace Natalia Br Sitepu',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S20051',
                'nama' => 'Cheilint Claudina Siallagan',
                'angkatan' => 2020,
                'status' => 'Aktif',
            ],

            // 2021
            [
                'nim' => '11S21001',
                'nama' => 'David Vincent Gurning',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21002',
                'nama' => 'Rifqi Haikal Chairiansyah',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21003',
                'nama' => 'Benhard Yudha',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21004',
                'nama' => 'Riris Iyut Roito Siregar',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21005',
                'nama' => 'Tesalonika Aprisda Br Sitopu',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21006',
                'nama' => 'Salwa Zahira Sofa Harahap',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21007',
                'nama' => 'Tiara Yuliandari',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21008',
                'nama' => 'Missyolin Eunike Rungguni Samosir',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21009',
                'nama' => 'Yose Putra Sambora Siagian',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21010',
                'nama' => 'Gabriel Cesar Hutagalung',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21011',
                'nama' => 'Archico Darius Simpar Sembiring',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21012',
                'nama' => 'Dwi Paranggi Purba',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21014',
                'nama' => 'Dedi Andre Martua Raja Panggabean',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21015',
                'nama' => 'Gerald Nathanael',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21016',
                'nama' => 'Putri Ayu Manurung',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21017',
                'nama' => 'Dea Yova Septi Saragih',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21018',
                'nama' => 'Syalom Advensia Manurung',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21019',
                'nama' => 'Agustina Veronika Butar Butar',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21020',
                'nama' => 'Intan Rumondang Sinaga',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21021',
                'nama' => 'Naomi Deva Theeresia Sihombing',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21023',
                'nama' => 'Yefta MIranda THreemarchie. S',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21024',
                'nama' => 'Robert Mangaratua Aritonang',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21025',
                'nama' => 'Boy Martahan Sitorus',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21027',
                'nama' => 'Derik Damero Sianipar',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21028',
                'nama' => 'Rafael A. C. Manurung',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21031',
                'nama' => 'Theo Samuel Dicunawi Aritonang',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21033',
                'nama' => 'Rio Eka Pasaribu',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21034',
                'nama' => 'Enrico Hezkiel Sirait',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21035',
                'nama' => 'Nicholas Hutabarat',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21037',
                'nama' => 'Dastin Raynold Sirait',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21038',
                'nama' => 'Jayfline Elia Jaddy Hutagalung',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21039',
                'nama' => 'Hanny Yosephine Br. Kaban',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21040',
                'nama' => 'Agnes Cicilia Marbun',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21041',
                'nama' => 'Itha Clarina Br. Tarigan',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21042',
                'nama' => 'Pany Irene Matondang',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21043',
                'nama' => 'Nada Hitado Bakara',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21044',
                'nama' => 'Icha Stevani Br Samosir',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21045',
                'nama' => 'Cindy Feronica Simangunsong',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21046',
                'nama' => 'Riskia Naomi Sitorus',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21047',
                'nama' => 'Corry Betriks Sitorus',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21048',
                'nama' => 'Angelika Ruth Sebrina Simatupang',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21049',
                'nama' => 'Tabitha Aquila Lamsari Marbun',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21050',
                'nama' => 'Ella Tasya Marito Silaban',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21051',
                'nama' => 'Wilona Diva Artha Simbolon',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21052',
                'nama' => 'Emely Angelica Lestari',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21053',
                'nama' => 'Grase Thessalonika Panjaitan',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21054',
                'nama' => 'Anni Octavia Simorangkir',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S21055',
                'nama' => 'Gerry Benyamin Abdiel Bukit',
                'angkatan' => 2021,
                'status' => 'Aktif',
            ],

            // 2022
            [
                'nim' => '11S22001',
                'nama' => 'Yan Rikho Siallagan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22002',
                'nama' => 'Joel Bonar Septian Sinambela',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22003',
                'nama' => 'Ralphael Zefanya Siahaan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22004',
                'nama' => 'Pangeran Simamora',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22005',
                'nama' => 'Olga Frischila G',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22006',
                'nama' => 'Febiola Cindy Valentina Tampubolon',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22007',
                'nama' => 'Patricia Agustin Sibarani',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22008',
                'nama' => 'Dhea Grace A. Simanjuntak',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22009',
                'nama' => 'William Julio Hasiholan Jaya Napitupulu',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22010',
                'nama' => 'Christian Theofani Napitupulu',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22011',
                'nama' => 'Jonathan Martinus Pangaribuan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22012',
                'nama' => 'Baha Ambrosius Sibarani',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22013',
                'nama' => 'Gabriela Amelia Silitonga',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22014',
                'nama' => 'Fretty Debora Sirait',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22015',
                'nama' => 'Dwi Lady Pandiangan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22016',
                'nama' => 'Deak Marujar Napitupulu',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22017',
                'nama' => 'Maria Laura Nasution',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22018',
                'nama' => 'Rachel Putri S. Br Nababan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22019',
                'nama' => 'Grace Alvani S. Simanullang',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22020',
                'nama' => 'Yessi Sitanggang',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22021',
                'nama' => 'Gracesia Romauli Marbun',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22022',
                'nama' => 'Martha Yulinda Lbn Tobing',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22023',
                'nama' => 'Riovan Samuel Sihombing',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22024',
                'nama' => 'Kevin Aditia Armando Harianja',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22025',
                'nama' => 'Wesly Baretta Siahaan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22026',
                'nama' => 'Gabriel Beriman Sigalingging',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22027',
                'nama' => 'Mario Agustin Sijabat',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22028',
                'nama' => 'Bertrand Cornelius Sianipar',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22029',
                'nama' => 'Roy Jonathan Hutajulu',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22030',
                'nama' => 'Chalvin Eric Melkishaer Sihombing',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22031',
                'nama' => 'Joel Chandio P. C. Aritonang',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22032',
                'nama' => 'Glen Sofian Pardede',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22033',
                'nama' => 'Rohit Panjaitan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22034',
                'nama' => 'Samuel Duilany Parreira Sibarani',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22035',
                'nama' => 'Yizreel Schwartz Sipahutar',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22036',
                'nama' => 'Prans Daniel Simarmata',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22037',
                'nama' => 'Ferdinand Martua Sihombing',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22038',
                'nama' => 'Viktris Maria Kristriani Lubis',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22039',
                'nama' => 'Kristina Anggriani Marbun',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22040',
                'nama' => 'Esra Medi Rosdina Silaen',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22041',
                'nama' => 'Sunanda Erika N. Munthe',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22042',
                'nama' => 'Lusiana Silaen',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22043',
                'nama' => 'Dian Grecia Natalie Gulo',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22044',
                'nama' => 'Okdini Nigita Hutagalung',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22045',
                'nama' => 'Angel Lampita Lubis',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22046',
                'nama' => 'Ruth Fidia Siregar',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22047',
                'nama' => 'Nadia Artha Gracia Sirait',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22048',
                'nama' => 'Agnes Yosepha Naibaho',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22049',
                'nama' => 'Tabita Novi Sinaga',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22050',
                'nama' => 'Charlos Pardomuan Purba',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22051',
                'nama' => 'Hermon Ronitua Sipahutar',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22052',
                'nama' => 'Yan Rikho Siallagan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22053',
                'nama' => 'Joel Bonar Septian Sinambela',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22054',
                'nama' => 'Ralphael Zefanya Siahaan',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
            [
                'nim' => '11S22055',
                'nama' => 'Pangeran Simamora',
                'angkatan' => 2022,
                'status' => 'Aktif',
            ],
        ]);
    }
}
